/**
 * Curated list of well-known universities for instant load (no network).
 * Format: [name, country]; sorted by name for binary search / display.
 */
export type UniversityEntry = { name: string; country: string }

export const BUNDLED_UNIVERSITIES: UniversityEntry[] = [
  { name: 'Australian National University', country: 'Australia' },
  { name: 'Boston University', country: 'United States' },
  { name: 'Brown University', country: 'United States' },
  { name: 'California Institute of Technology', country: 'United States' },
  { name: 'Cambridge University', country: 'United Kingdom' },
  { name: 'Carnegie Mellon University', country: 'United States' },
  { name: 'Columbia University', country: 'United States' },
  { name: 'Cornell University', country: 'United States' },
  { name: 'Duke University', country: 'United States' },
  { name: 'ETH Zurich', country: 'Switzerland' },
  { name: 'Georgia Institute of Technology', country: 'United States' },
  { name: 'Harvard University', country: 'United States' },
  { name: 'Imperial College London', country: 'United Kingdom' },
  { name: 'Indian Institute of Technology Bombay', country: 'India' },
  { name: 'Indian Institute of Technology Delhi', country: 'India' },
  { name: 'Indian Institute of Technology Madras', country: 'India' },
  { name: 'Johns Hopkins University', country: 'United States' },
  { name: 'London School of Economics', country: 'United Kingdom' },
  { name: 'Massachusetts Institute of Technology', country: 'United States' },
  { name: 'McGill University', country: 'Canada' },
  { name: 'National University of Singapore', country: 'Singapore' },
  { name: 'Northwestern University', country: 'United States' },
  { name: 'New York University', country: 'United States' },
  { name: 'Oxford University', country: 'United Kingdom' },
  { name: 'Princeton University', country: 'United States' },
  { name: 'Stanford University', country: 'United States' },
  { name: 'Technical University of Munich', country: 'Germany' },
  { name: 'University of California Berkeley', country: 'United States' },
  { name: 'University of California Los Angeles', country: 'United States' },
  { name: 'University of Chicago', country: 'United States' },
  { name: 'University of Edinburgh', country: 'United Kingdom' },
  { name: 'University of Hong Kong', country: 'Hong Kong' },
  { name: 'University of Illinois Urbana-Champaign', country: 'United States' },
  { name: 'University of Melbourne', country: 'Australia' },
  { name: 'University of Michigan', country: 'United States' },
  { name: 'University of Pennsylvania', country: 'United States' },
  { name: 'University of Texas at Austin', country: 'United States' },
  { name: 'University of Toronto', country: 'Canada' },
  { name: 'University of Washington', country: 'United States' },
  { name: 'University of Waterloo', country: 'Canada' },
  { name: 'Yale University', country: 'United States' },
  { name: 'Delft University of Technology', country: 'Netherlands' },
  { name: 'École Polytechnique', country: 'France' },
  { name: 'École Normale Supérieure', country: 'France' },
  { name: 'King\'s College London', country: 'United Kingdom' },
  { name: 'KU Leuven', country: 'Belgium' },
  { name: 'Ludwig Maximilian University of Munich', country: 'Germany' },
  { name: 'Monash University', country: 'Australia' },
  { name: 'Ohio State University', country: 'United States' },
  { name: 'Penn State University', country: 'United States' },
  { name: 'Purdue University', country: 'United States' },
  { name: 'Rice University', country: 'United States' },
  { name: 'Seoul National University', country: 'South Korea' },
  { name: 'Shanghai Jiao Tong University', country: 'China' },
  { name: 'Sorbonne University', country: 'France' },
  { name: 'Tsinghua University', country: 'China' },
  { name: 'UCL', country: 'United Kingdom' },
  { name: 'University of British Columbia', country: 'Canada' },
  { name: 'University of California San Diego', country: 'United States' },
  { name: 'University of Cambridge', country: 'United Kingdom' },
  { name: 'University of Oxford', country: 'United Kingdom' },
  { name: 'University of Science and Technology of China', country: 'China' },
  { name: 'University of Sydney', country: 'Australia' },
  { name: 'University of Tokyo', country: 'Japan' },
  { name: 'University of Wisconsin-Madison', country: 'United States' },
  { name: 'Beijing University', country: 'China' },
  { name: 'BITS Pilani', country: 'India' },
  { name: 'Boston College', country: 'United States' },
  { name: 'California State University', country: 'United States' },
  { name: 'City University of Hong Kong', country: 'Hong Kong' },
  { name: 'Dartmouth College', country: 'United States' },
  { name: 'Emory University', country: 'United States' },
  { name: 'Florida State University', country: 'United States' },
  { name: 'Free University of Berlin', country: 'Germany' },
  { name: 'Heidelberg University', country: 'Germany' },
  { name: 'Hong Kong University of Science and Technology', country: 'Hong Kong' },
  { name: 'Kyoto University', country: 'Japan' },
  { name: 'Leiden University', country: 'Netherlands' },
  { name: 'McMaster University', country: 'Canada' },
  { name: 'Michigan State University', country: 'United States' },
  { name: 'Nanyang Technological University', country: 'Singapore' },
  { name: 'North Carolina State University', country: 'United States' },
  { name: 'Queen Mary University of London', country: 'United Kingdom' },
  { name: 'Rutgers University', country: 'United States' },
  { name: 'Texas A&M University', country: 'United States' },
  { name: 'University of Amsterdam', country: 'Netherlands' },
  { name: 'University of Arizona', country: 'United States' },
  { name: 'University of Bristol', country: 'United Kingdom' },
  { name: 'University of California Davis', country: 'United States' },
  { name: 'University of California Irvine', country: 'United States' },
  { name: 'University of Colorado Boulder', country: 'United States' },
  { name: 'University of Florida', country: 'United States' },
  { name: 'University of Glasgow', country: 'United Kingdom' },
  { name: 'University of Maryland', country: 'United States' },
  { name: 'University of Minnesota', country: 'United States' },
  { name: 'University of North Carolina Chapel Hill', country: 'United States' },
  { name: 'University of Pittsburgh', country: 'United States' },
  { name: 'University of Southern California', country: 'United States' },
  { name: 'University of Virginia', country: 'United States' },
  { name: 'Vanderbilt University', country: 'United States' },
  { name: 'Virginia Tech', country: 'United States' },
  { name: 'Vrije Universiteit Amsterdam', country: 'Netherlands' },
  { name: 'Washington University in St. Louis', country: 'United States' },
  { name: 'Arizona State University', country: 'United States' },
  { name: 'Baylor University', country: 'United States' },
  { name: 'Brigham Young University', country: 'United States' },
  { name: 'Case Western Reserve University', country: 'United States' },
  { name: 'Drexel University', country: 'United States' },
  { name: 'George Mason University', country: 'United States' },
  { name: 'Georgetown University', country: 'United States' },
  { name: 'Indiana University', country: 'United States' },
  { name: 'Iowa State University', country: 'United States' },
  { name: 'Notre Dame University', country: 'United States' },
  { name: 'Ohio University', country: 'United States' },
  { name: 'Oregon State University', country: 'United States' },
  { name: 'San Diego State University', country: 'United States' },
  { name: 'Stony Brook University', country: 'United States' },
  { name: 'Syracuse University', country: 'United States' },
  { name: 'Temple University', country: 'United States' },
  { name: 'Tufts University', country: 'United States' },
  { name: 'University of Connecticut', country: 'United States' },
  { name: 'University of Iowa', country: 'United States' },
  { name: 'University of Kansas', country: 'United States' },
  { name: 'University of Massachusetts Amherst', country: 'United States' },
  { name: 'University of Miami', country: 'United States' },
  { name: 'University of Notre Dame', country: 'United States' },
  { name: 'University of Oregon', country: 'United States' },
  { name: 'University of Rochester', country: 'United States' },
  { name: 'University of Utah', country: 'United States' },
  { name: 'Wake Forest University', country: 'United States' },
  { name: 'William & Mary', country: 'United States' },
  { name: 'Birmingham University', country: 'United Kingdom' },
  { name: 'Bristol University', country: 'United Kingdom' },
  { name: 'Durham University', country: 'United Kingdom' },
  { name: 'Leeds University', country: 'United Kingdom' },
  { name: 'Manchester University', country: 'United Kingdom' },
  { name: 'Sheffield University', country: 'United Kingdom' },
  { name: 'Southampton University', country: 'United Kingdom' },
  { name: 'Warwick University', country: 'United Kingdom' },
  { name: 'York University', country: 'United Kingdom' },
  { name: 'Alberta University', country: 'Canada' },
  { name: 'McMaster University', country: 'Canada' },
  { name: 'Queen\'s University', country: 'Canada' },
  { name: 'Simon Fraser University', country: 'Canada' },
  { name: 'University of Calgary', country: 'Canada' },
  { name: 'University of Montreal', country: 'Canada' },
  { name: 'University of Queensland', country: 'Australia' },
  { name: 'University of Western Australia', country: 'Australia' },
  { name: 'Delhi University', country: 'India' },
  { name: 'Jawaharlal Nehru University', country: 'India' },
  { name: 'IIT Kharagpur', country: 'India' },
  { name: 'IIT Kanpur', country: 'India' },
  { name: 'BITS Goa', country: 'India' },
  { name: 'Tata Institute of Fundamental Research', country: 'India' },
].sort((a, b) => a.name.localeCompare(b.name))
